services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container
    depends_on:
      - postgres-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      SHOW_SQL: ${SHOW_SQL}
      FORMAT_SQL: ${FORMAT_SQL}
      DATABASE: ${DATABASE}
      DIALECT: ${DIALECT}
    networks:
      - my-net
    ports:
      - "8080:8080"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - my-net

networks:
  my-net:
